window.LB_CONTENT = {
  "version": "3.1",
  "site": {
    "wallpaper": "assets/fond-atelier.jpg",
    "contactEmail": "labidouille@atomicmail.io",
    "authorName": "Leny",
    "profileImage": "assets/logo-la-bidouille.png",
    "logo": "assets/logo-la-bidouille.png",
    "bio": "Moi, c'est Leny. La rétro-informatique, les anciennes consoles, les réparations, les mods et toutes les bidouilles qui redonnent vie au matériel d'autrefois sont une vraie passion pour moi.",
    "about": "La Bidouille est mon atelier numérique : j'y partage mes vidéos, mes restaurations, mes découvertes, mes fichiers utiles et mes projets autour du rétro."
  },
  "videos": {
    "tutoriels": [],
    "reparations": [],
    "mods": []
  },
  "downloads": [
    {
      "title": "retrobat",
      "category": "Émulation",
      "description": "émulateur retrobat Windows mac et linux que j'utilise personnellement et qui et très bien",
      "fileUrl": "https://github.com/RetroBat-Official/retrobat/releases",
      "image": "https://www.retrobat.org/wp-content/uploads/2026/03/image-768x431.webp",
      "version": "V8.2",
      "size": "8go"
    }
  ],
  "gallery": [
    {
      "title": "La Bidouille",
      "caption": "Rétro, tech et passion — le logo de l'atelier de Leny.",
      "album": "Identité",
      "image": "assets/logo-la-bidouille.png"
    }
  ],
  "games": [
    {
      "title": "Ping 95",
      "description": "Un jeu de raquettes original créé pour La Bidouille OS. Joue au clavier ou avec les commandes tactiles et marque 7 points avant l'ordinateur.",
      "url": "jeux/ping-95/index.html",
      "image": "assets/Capture d'écran 2026-08-09 201249.png",
      "mode": "embed",
      "ready": true
    },
    {
      "title": "PAC-MAN — Google Doodle officiel",
      "description": "La version jouable officielle créée par Google avec l'autorisation de Bandai Namco pour les 30 ans de PAC-MAN. Elle s'ouvre sur le site officiel de Google Doodles.",
      "url": "https://www.google.com/logos/2010/pacman10-i.html",
      "image": "assets/Capture d'écran 2026-08-09 201849.png",
      "mode": "external",
      "ready": true
    }
  ],
  "consoles": [
    {
      "name": "Magnavox Odyssey",
      "manufacturer": "Magnavox",
      "release": "1972",
      "region": "Amérique du Nord",
      "generation": "Première génération",
      "type": "Salon",
      "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Magnavox-Odyssey-Console-Set.jpg?width=640",
      "imageSource": "https://commons.wikimedia.org/wiki/File:Magnavox-Odyssey-Console-Set.jpg",
      "summary": "La première console de salon commercialisée. Elle produit des formes très simples et utilise des calques transparents posés sur le téléviseur.",
      "cpu": "Aucun microprocesseur : circuits analogiques et logiques",
      "graphics": "Signal noir et blanc, sans génération de score ni décor",
      "memory": "Aucune mémoire informatique classique",
      "media": "Cartes de connexion internes et accessoires physiques",
      "display": "Téléviseur, formes lumineuses monochromes",
      "sound": "Aucun son généré par la console",
      "contemporaries": "Pong en arcade (1972), premières consoles Pong dédiées"
    },
    {
      "name": "Atari 2600",
      "manufacturer": "Atari",
      "release": "1977",
      "region": "Amérique du Nord, puis Europe et Japon",
      "generation": "Deuxième génération",
      "type": "Salon",
      "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Atari-2600-Wood-4Sw-Set.jpg?width=640",
      "imageSource": "https://commons.wikimedia.org/wiki/File:Atari-2600-Wood-4Sw-Set.jpg",
      "summary": "Une console à cartouches déterminante dans l'histoire du jeu vidéo domestique, connue pour son joystick à un bouton.",
      "cpu": "MOS 6507, environ 1,19 MHz en NTSC",
      "graphics": "Puce Television Interface Adaptor (TIA)",
      "memory": "128 octets de RAM interne",
      "media": "Cartouches ROM",
      "display": "Résolution et couleurs pilotées ligne par ligne par le programme",
      "sound": "Deux canaux via la TIA",
      "contemporaries": "Fairchild Channel F, Intellivision, Odyssey²"
    },
    {
      "name": "ColecoVision",
      "manufacturer": "Coleco",
      "release": "1982",
      "region": "Amérique du Nord et Europe",
      "generation": "Deuxième génération",
      "type": "Salon",
      "image": "https://commons.wikimedia.org/wiki/Special:FilePath/ColecoVision-wController-L.jpg?width=640",
      "imageSource": "https://commons.wikimedia.org/wiki/File:ColecoVision-wController-L.jpg",
      "summary": "Une machine réputée pour ses adaptations d'arcade très proches des bornes du début des années 1980.",
      "cpu": "Zilog Z80A, 3,58 MHz",
      "graphics": "Texas Instruments TMS9928A",
      "memory": "1 Kio de RAM, 16 Kio de mémoire vidéo",
      "media": "Cartouches ROM",
      "display": "Jusqu'à 256 × 192 pixels, 16 couleurs",
      "sound": "Texas Instruments SN76489A, 3 voix et bruit",
      "contemporaries": "Atari 5200, Vectrex, Intellivision"
    },
    {
      "name": "Nintendo Entertainment System",
      "manufacturer": "Nintendo",
      "release": "1983 au Japon, 1985 en Amérique du Nord, 1986–1987 en Europe",
      "region": "Japon, Amérique du Nord et Europe",
      "generation": "Troisième génération — 8 bits",
      "type": "Salon",
      "image": "https://commons.wikimedia.org/wiki/Special:FilePath/NES-Console-Set.jpg?width=640",
      "imageSource": "https://commons.wikimedia.org/wiki/File:NES-Console-Set.jpg",
      "summary": "Sortie au Japon sous le nom Famicom, la NES a largement relancé le marché de la console de salon en Amérique du Nord.",
      "cpu": "Ricoh 2A03/2A07 dérivé du MOS 6502, environ 1,79 MHz en NTSC",
      "graphics": "PPU Ricoh dédiée",
      "memory": "2 Kio de RAM principale, 2 Kio de mémoire vidéo interne",
      "media": "Cartouches, parfois enrichies de puces supplémentaires",
      "display": "256 × 240 pixels, palette de 54 couleurs utilisables",
      "sound": "5 canaux intégrés au processeur en version occidentale",
      "contemporaries": "Sega SG-1000, Master System, Atari 7800"
    },
    {
      "name": "Sega Master System",
      "manufacturer": "Sega",
      "release": "1985 au Japon, 1986 en Amérique du Nord, 1987 en Europe",
      "region": "Monde",
      "generation": "Troisième génération — 8 bits",
      "type": "Salon",
      "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Sega-Master-System-Set.jpg?width=640",
      "imageSource": "https://commons.wikimedia.org/wiki/File:Sega-Master-System-Set.jpg",
      "summary": "La console 8 bits de Sega, particulièrement populaire en Europe et au Brésil.",
      "cpu": "Zilog Z80A, environ 3,58 MHz",
      "graphics": "VDP dérivé de la famille TMS9918 avec modes Sega",
      "memory": "8 Kio de RAM, 16 Kio de mémoire vidéo",
      "media": "Cartouches et cartes Sega Card selon les modèles",
      "display": "Jusqu'à 256 × 192 pixels, 32 couleurs simultanées",
      "sound": "PSG SN76489 ; FM YM2413 sur certains modèles japonais",
      "contemporaries": "NES/Famicom, Atari 7800"
    },
    {
      "name": "PC Engine / TurboGrafx-16",
      "manufacturer": "NEC et Hudson Soft",
      "release": "1987 au Japon, 1989 en Amérique du Nord",
      "region": "Japon, Amérique du Nord et quelques marchés européens",
      "generation": "Quatrième génération",
      "type": "Salon",
      "image": "https://commons.wikimedia.org/wiki/Special:FilePath/PC-Engine-Console-Set.jpg?width=640",
      "imageSource": "https://commons.wikimedia.org/wiki/File:PC-Engine-Console-Set.jpg",
      "summary": "Une petite console à processeur principal 8 bits et circuit graphique 16 bits, pionnière du CD-ROM sur console.",
      "cpu": "Hudson HuC6280, jusqu'à 7,16 MHz",
      "graphics": "HuC6270 VDC et HuC6260 encodeur couleur",
      "memory": "8 Kio de RAM principale, 64 Kio de mémoire vidéo",
      "media": "HuCard ; CD-ROM² avec extension",
      "display": "Plusieurs modes, généralement autour de 256 × 224 pixels",
      "sound": "6 canaux à table d'ondes",
      "contemporaries": "Mega Drive, Super Famicom, Neo Geo AES"
    },
    {
      "name": "Sega Mega Drive / Genesis",
      "manufacturer": "Sega",
      "release": "1988 au Japon, 1989 en Amérique du Nord, 1990 en Europe",
      "region": "Monde",
      "generation": "Quatrième génération — 16 bits",
      "type": "Salon",
      "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Sega-Mega-Drive-JP-Mk1-Console-Set.jpg?width=640",
      "imageSource": "https://commons.wikimedia.org/wiki/File:Sega-Mega-Drive-JP-Mk1-Console-Set.jpg",
      "summary": "La 16 bits de Sega, appelée Genesis en Amérique du Nord, célèbre pour ses jeux rapides et ses nombreux accessoires.",
      "cpu": "Motorola 68000 autour de 7,6 MHz, assisté d'un Z80",
      "graphics": "VDP Sega avec plans de défilement et sprites",
      "memory": "64 Kio de RAM principale, 64 Kio de mémoire vidéo",
      "media": "Cartouches ; Mega-CD et 32X en extensions",
      "display": "Modes courants 320 × 224 ou 256 × 224 pixels",
      "sound": "Yamaha YM2612 et PSG SN76489",
      "contemporaries": "Super Nintendo, PC Engine, Neo Geo AES"
    },
    {
      "name": "Nintendo Game Boy",
      "manufacturer": "Nintendo",
      "release": "1989",
      "region": "Monde",
      "generation": "Quatrième génération — portable",
      "type": "Portable",
      "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Game-Boy-FL.jpg?width=640",
      "imageSource": "https://commons.wikimedia.org/wiki/File:Game-Boy-FL.jpg",
      "summary": "Une portable monochrome robuste et très autonome, dont la ludothèque et le câble Link ont marqué toute une génération.",
      "cpu": "Sharp LR35902, 4,19 MHz",
      "graphics": "Circuit intégré au système",
      "memory": "8 Kio de RAM, 8 Kio de mémoire vidéo",
      "media": "Cartouches Game Pak",
      "display": "160 × 144 pixels, 4 nuances",
      "sound": "4 canaux stéréo",
      "contemporaries": "Atari Lynx, Sega Game Gear, PC Engine GT"
    },
    {
      "name": "Atari Lynx",
      "manufacturer": "Atari",
      "release": "1989",
      "region": "Amérique du Nord et Europe",
      "generation": "Quatrième génération — portable",
      "type": "Portable",
      "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Atari-Lynx-I-Handheld.jpg?width=640",
      "imageSource": "https://commons.wikimedia.org/wiki/File:Atari-Lynx-I-Handheld.jpg",
      "summary": "Une portable couleur puissante pour son époque, capable notamment de zooms matériels et de jeu en réseau local.",
      "cpu": "WDC 65SC02, 4 MHz",
      "graphics": "Puces Mikey et Suzy",
      "memory": "64 Kio de RAM",
      "media": "Cartes mémoire propriétaires",
      "display": "160 × 102 pixels, 16 couleurs parmi 4096",
      "sound": "4 canaux",
      "contemporaries": "Game Boy, Game Gear, PC Engine GT"
    },
    {
      "name": "Super Nintendo / Super Famicom",
      "manufacturer": "Nintendo",
      "release": "1990 au Japon, 1991 en Amérique du Nord, 1992 en Europe",
      "region": "Monde",
      "generation": "Quatrième génération — 16 bits",
      "type": "Salon",
      "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Super-Famicom-Console-Set.jpg?width=640",
      "imageSource": "https://commons.wikimedia.org/wiki/File:Super-Famicom-Console-Set.jpg",
      "summary": "La 16 bits de Nintendo, connue pour son Mode 7, son circuit sonore et les puces spéciales intégrées à certaines cartouches.",
      "cpu": "Ricoh 5A22 dérivé du 65C816, jusqu'à environ 3,58 MHz",
      "graphics": "Deux PPU dédiées",
      "memory": "128 Kio de RAM principale, 64 Kio de mémoire vidéo",
      "media": "Cartouches, parfois avec coprocesseur",
      "display": "Modes de 256 × 224 à 512 × 448 pixels",
      "sound": "Sony SPC700 et DSP, 8 canaux échantillonnés",
      "contemporaries": "Mega Drive, PC Engine, Neo Geo AES"
    },
    {
      "name": "Sega Game Gear",
      "manufacturer": "Sega",
      "release": "1990 au Japon, 1991 en Europe",
      "region": "Monde",
      "generation": "Quatrième génération — portable",
      "type": "Portable",
      "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Sega-Game-Gear-WB.jpg?width=640",
      "imageSource": "https://commons.wikimedia.org/wiki/File:Sega-Game-Gear-WB.jpg",
      "summary": "Une portable couleur proche techniquement de la Master System, aujourd'hui souvent restaurée à cause de condensateurs vieillissants.",
      "cpu": "Zilog Z80, environ 3,58 MHz",
      "graphics": "VDP dérivé de la Master System",
      "memory": "8 Kio de RAM, 16 Kio de mémoire vidéo",
      "media": "Cartouches Game Gear",
      "display": "160 × 144 pixels, 32 couleurs simultanées",
      "sound": "PSG 4 canaux stéréo",
      "contemporaries": "Game Boy, Atari Lynx, PC Engine GT"
    },
    {
      "name": "Neo Geo AES",
      "manufacturer": "SNK",
      "release": "1990",
      "region": "Japon, Amérique du Nord et Europe",
      "generation": "Quatrième génération",
      "type": "Salon",
      "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Neo-Geo-AES-Console-Set.jpg?width=640",
      "imageSource": "https://commons.wikimedia.org/wiki/File:Neo-Geo-AES-Console-Set.jpg",
      "summary": "La version domestique du système d'arcade Neo Geo MVS, avec des cartouches très volumineuses et une restitution proche de la borne.",
      "cpu": "Motorola 68000 à 12 MHz et Zilog Z80 à 4 MHz",
      "graphics": "Circuit SNK orienté sprites",
      "memory": "64 Kio de RAM principale et mémoires spécialisées",
      "media": "Cartouches AES",
      "display": "320 × 224 pixels, jusqu'à 4096 couleurs simultanées",
      "sound": "Yamaha YM2610, synthèse et échantillons",
      "contemporaries": "Mega Drive, Super Nintendo, PC Engine"
    },
    {
      "name": "3DO Interactive Multiplayer",
      "manufacturer": "The 3DO Company, modèles Panasonic et autres",
      "release": "1993",
      "region": "Japon, Amérique du Nord et Europe",
      "generation": "Cinquième génération — 32 bits",
      "type": "Salon",
      "image": "https://commons.wikimedia.org/wiki/Special:FilePath/3DO-FZ1-Console-Set.jpg?width=640",
      "imageSource": "https://commons.wikimedia.org/wiki/File:3DO-FZ1-Console-Set.jpg",
      "summary": "Une plateforme multimédia sous licence, fabriquée par plusieurs entreprises et centrée sur le CD-ROM.",
      "cpu": "ARM60, 12,5 MHz",
      "graphics": "Deux coprocesseurs graphiques personnalisés",
      "memory": "2 Mio de RAM principale, 1 Mio de mémoire vidéo",
      "media": "CD-ROM",
      "display": "Sortie vidéo entrelacée, rendu 2D et 3D accéléré",
      "sound": "DSP audio 16 bits",
      "contemporaries": "Atari Jaguar, Amiga CD32, premières Saturn et PlayStation"
    },
    {
      "name": "Atari Jaguar",
      "manufacturer": "Atari",
      "release": "1993",
      "region": "Amérique du Nord et Europe",
      "generation": "Cinquième génération",
      "type": "Salon",
      "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Atari-Jaguar-Console-Set.jpg?width=640",
      "imageSource": "https://commons.wikimedia.org/wiki/File:Atari-Jaguar-Console-Set.jpg",
      "summary": "La dernière console de salon d'Atari, bâtie autour de plusieurs processeurs spécialisés et commercialisée comme une machine 64 bits.",
      "cpu": "Motorola 68000 et processeurs RISC Tom/Jerry",
      "graphics": "Object Processor, Blitter et GPU personnalisés",
      "memory": "2 Mio de RAM",
      "media": "Cartouches ; CD-ROM avec l'extension Jaguar CD",
      "display": "Rendu 2D et 3D selon les logiciels",
      "sound": "DSP Jerry",
      "contemporaries": "3DO, Amiga CD32, Saturn, PlayStation"
    },
    {
      "name": "Sega Saturn",
      "manufacturer": "Sega",
      "release": "1994 au Japon, 1995 en Europe et Amérique du Nord",
      "region": "Monde",
      "generation": "Cinquième génération — 32 bits",
      "type": "Salon",
      "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Sega-Saturn-Console-Set-Mk1.jpg?width=640",
      "imageSource": "https://commons.wikimedia.org/wiki/File:Sega-Saturn-Console-Set-Mk1.jpg",
      "summary": "Une architecture complexe à deux processeurs, très à l'aise en 2D et dotée d'une ludothèque japonaise particulièrement riche.",
      "cpu": "Deux Hitachi SH-2 à environ 28,6 MHz",
      "graphics": "VDP1 pour sprites/polygones et VDP2 pour les plans",
      "memory": "2 Mio de RAM principale, environ 1,5 Mio de mémoire vidéo",
      "media": "CD-ROM et cartouches d'extension",
      "display": "Nombreux modes 2D et 3D, jusqu'aux résolutions entrelacées",
      "sound": "Motorola 68000 audio et Yamaha SCSP, 32 canaux",
      "contemporaries": "PlayStation, Nintendo 64, 3DO"
    },
    {
      "name": "Sony PlayStation",
      "manufacturer": "Sony Computer Entertainment",
      "release": "1994 au Japon, 1995 en Europe et Amérique du Nord",
      "region": "Monde",
      "generation": "Cinquième génération — 32 bits",
      "type": "Salon",
      "image": "https://commons.wikimedia.org/wiki/Special:FilePath/PSX-Console-wController.jpg?width=640",
      "imageSource": "https://commons.wikimedia.org/wiki/File:PSX-Console-wController.jpg",
      "summary": "La première console PlayStation a démocratisé la 3D sur CD-ROM et accueilli une immense variété de jeux.",
      "cpu": "MIPS R3000A compatible, environ 33,9 MHz",
      "graphics": "GPU personnalisé Sony",
      "memory": "2 Mio de RAM, 1 Mio de mémoire vidéo, 512 Kio de RAM audio",
      "media": "CD-ROM et cartes mémoire externes",
      "display": "Modes de 256 × 224 à 640 × 480 pixels",
      "sound": "24 canaux ADPCM",
      "contemporaries": "Sega Saturn, Nintendo 64, Atari Jaguar"
    },
    {
      "name": "Nintendo 64",
      "manufacturer": "Nintendo",
      "release": "1996 au Japon et en Amérique du Nord, 1997 en Europe",
      "region": "Monde",
      "generation": "Cinquième génération — 64 bits",
      "type": "Salon",
      "image": "https://commons.wikimedia.org/wiki/Special:FilePath/N64-Console-Set.jpg?width=640",
      "imageSource": "https://commons.wikimedia.org/wiki/File:N64-Console-Set.jpg",
      "summary": "La console 64 bits de Nintendo reste associée à sa manette atypique, au stick analogique et à des jeux 3D fondateurs.",
      "cpu": "NEC VR4300 compatible MIPS, 93,75 MHz",
      "graphics": "Reality Co-Processor conçu avec SGI",
      "memory": "4 Mio de RDRAM unifiée, extensible à 8 Mio",
      "media": "Cartouches ; disques 64DD au Japon",
      "display": "Résolutions variables jusqu'à 640 × 480 pixels",
      "sound": "Traitement audio par le Reality Signal Processor",
      "contemporaries": "PlayStation, Sega Saturn"
    },
    {
      "name": "Sega Dreamcast",
      "manufacturer": "Sega",
      "release": "1998 au Japon, 1999 en Europe et Amérique du Nord",
      "region": "Monde",
      "generation": "Sixième génération — 128 bits commerciaux",
      "type": "Salon",
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Dreamcast-Console-Set.png/250px-Dreamcast-Console-Set.png?utm_source=fr.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
      "imageSource": "https://commons.wikimedia.org/wiki/File:Sega-Dreamcast-Console-Set.jpg",
      "summary": "La dernière console de Sega, équipée d'un modem selon les régions et pensée très tôt pour le jeu en ligne.",
      "cpu": "Hitachi SH-4, 200 MHz",
      "graphics": "PowerVR2, environ 100 MHz",
      "memory": "16 Mio de RAM, 8 Mio de mémoire vidéo, 2 Mio de RAM audio",
      "media": "GD-ROM et CD audio",
      "display": "Sortie vidéo jusqu'à 640 × 480, VGA compatible avec de nombreux jeux",
      "sound": "Yamaha AICA, 64 canaux",
      "contemporaries": "PlayStation, puis PlayStation 2, GameCube et Xbox"
    },
    {
      "name": "Sony PlayStation 2",
      "manufacturer": "Sony Computer Entertainment",
      "release": "2000",
      "region": "Monde",
      "generation": "Sixième génération",
      "type": "Salon",
      "image": "https://commons.wikimedia.org/wiki/Special:FilePath/PS2-Fat-Console-Set.jpg?width=640",
      "imageSource": "https://commons.wikimedia.org/wiki/File:PS2-Fat-Console-Set.jpg",
      "summary": "Une console compatible avec une grande partie de la ludothèque PlayStation et dotée d'un lecteur DVD, devenue la plus vendue de sa génération.",
      "cpu": "Emotion Engine, environ 294 MHz sur les premiers modèles",
      "graphics": "Graphics Synthesizer, 4 Mio de mémoire embarquée",
      "memory": "32 Mio de RDRAM",
      "media": "DVD-ROM, CD-ROM, cartes mémoire",
      "display": "Nombreux modes entrelacés et progressifs selon les jeux",
      "sound": "SPU2, 48 canaux",
      "contemporaries": "Dreamcast, GameCube, Xbox"
    },
    {
      "name": "Nintendo GameCube",
      "manufacturer": "Nintendo",
      "release": "2001 au Japon et en Amérique du Nord, 2002 en Europe",
      "region": "Monde",
      "generation": "Sixième génération",
      "type": "Salon",
      "image": "https://commons.wikimedia.org/wiki/Special:FilePath/GameCube-Set.jpg?width=640",
      "imageSource": "https://commons.wikimedia.org/wiki/File:GameCube-Set.jpg",
      "summary": "Une console compacte à mini-disques, centrée sur le jeu local et reliée à la Game Boy Advance dans plusieurs titres.",
      "cpu": "IBM Gekko PowerPC, 485 MHz",
      "graphics": "ATI Flipper, 162 MHz",
      "memory": "24 Mio de 1T-SRAM principale et 16 Mio de mémoire auxiliaire",
      "media": "Disques optiques Nintendo de 8 cm, cartes mémoire",
      "display": "480i et 480p selon jeux et régions",
      "sound": "DSP Macronix, 64 canaux",
      "contemporaries": "PlayStation 2, Xbox, Dreamcast"
    },
    {
      "name": "Microsoft Xbox",
      "manufacturer": "Microsoft",
      "release": "2001 en Amérique du Nord, 2002 en Europe et au Japon",
      "region": "Monde",
      "generation": "Sixième génération",
      "type": "Salon",
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Xbox-Console-Set.png/250px-Xbox-Console-Set.png?utm_source=fr.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
      "imageSource": "https://commons.wikimedia.org/wiki/File:Xbox-Console-Set.jpg",
      "summary": "La première Xbox se distingue par son disque dur intégré, ses composants proches d'un PC et le lancement de Xbox Live.",
      "cpu": "Intel dérivé du Pentium III, 733 MHz",
      "graphics": "Nvidia NV2A, 233 MHz",
      "memory": "64 Mio de DDR unifiée",
      "media": "DVD-ROM, disque dur interne, cartes mémoire",
      "display": "De 480i à 1080i selon les jeux et régions",
      "sound": "Nvidia MCPX, Dolby Digital en jeu",
      "contemporaries": "PlayStation 2, GameCube, Dreamcast"
    },
    {
      "name": "Nintendo Game Boy Advance",
      "manufacturer": "Nintendo",
      "release": "2001",
      "region": "Monde",
      "generation": "Sixième génération — portable",
      "type": "Portable",
      "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Nintendo-Game-Boy-Advance-Purple-FL.jpg?width=640",
      "imageSource": "https://commons.wikimedia.org/wiki/File:Nintendo-Game-Boy-Advance-Purple-FL.jpg",
      "summary": "Une portable 32 bits rétrocompatible avec les jeux Game Boy et Game Boy Color sur ses premiers modèles.",
      "cpu": "ARM7TDMI, 16,78 MHz, avec processeur secondaire pour la compatibilité",
      "graphics": "Circuit 2D intégré avec plusieurs modes d'affichage",
      "memory": "32 Kio internes et 256 Kio externes, plus mémoires vidéo dédiées",
      "media": "Cartouches Game Boy Advance",
      "display": "240 × 160 pixels, 32 768 couleurs",
      "sound": "Canaux hérités de la Game Boy et deux canaux PCM",
      "contemporaries": "Neo Geo Pocket Color, WonderSwan Color"
    },
    {
      "name": "Nintendo DS",
      "manufacturer": "Nintendo",
      "release": "2004 en Amérique du Nord et au Japon, 2005 en Europe",
      "region": "Monde",
      "generation": "Septième génération — portable",
      "type": "Portable",
      "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Nintendo-DS-Fat-Blue.jpg?width=640",
      "imageSource": "https://commons.wikimedia.org/wiki/File:Nintendo-DS-Fat-Blue.jpg",
      "summary": "Une portable à deux écrans dont celui du bas est tactile, avec microphone, Wi-Fi et compatibilité Game Boy Advance sur les premiers modèles.",
      "cpu": "ARM946E-S à 67 MHz et ARM7TDMI à 33 MHz",
      "graphics": "Moteurs 2D et accélération 3D intégrés",
      "memory": "4 Mio de RAM principale",
      "media": "Cartes DS et cartouches GBA sur DS/DS Lite",
      "display": "Deux écrans 256 × 192 pixels, tactile résistif en bas",
      "sound": "16 canaux PCM/ADPCM",
      "contemporaries": "Sony PSP, Game Boy Advance"
    },
    {
      "name": "Sony PSP",
      "manufacturer": "Sony Computer Entertainment",
      "release": "2004 au Japon, 2005 en Europe et Amérique du Nord",
      "region": "Monde",
      "generation": "Septième génération — portable",
      "type": "Portable",
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/PSP-2000.jpg/250px-PSP-2000.jpg?utm_source=fr.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
      "imageSource": "https://commons.wikimedia.org/wiki/File:PSP-1000.jpg",
      "summary": "Une portable multimédia à grand écran 16:9, capable de jeux 3D ambitieux et utilisant le format optique UMD.",
      "cpu": "MIPS R4000, fréquence maximale de 333 MHz",
      "graphics": "Processeur graphique intégré, 166 MHz au maximum",
      "memory": "32 Mio de RAM sur PSP-1000, 64 Mio sur les modèles suivants",
      "media": "UMD et Memory Stick Pro Duo",
      "display": "480 × 272 pixels, écran 4,3 pouces",
      "sound": "Stéréo et traitement audio matériel",
      "contemporaries": "Nintendo DS, Game Boy Advance"
    }
  ]
};
